# Generated by Django 5.1.2 on 2024-10-30 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_degree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.degree'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='program',
            name='major',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.major'),
        ),
    ]
