# Generated by Django 5.1.2 on 2024-10-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_remove_degree_program_course_degree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='full_name',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
