# Generated by Django 5.1.2 on 2024-10-22 06:18

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_page_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.get_image_upload_path),
        ),
    ]
