# Generated by Django 5.1.2 on 2024-10-22 06:38

import pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_slide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.get_slide_upload_path),
        ),
    ]
