# Generated by Django 5.1.2 on 2024-10-30 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='prefix_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('fname_th', models.CharField(max_length=150, verbose_name='ชื่อ (ภาษาไทย)')),
                ('lname_th', models.CharField(max_length=150, verbose_name='สกุล (ภาษาไทย)')),
                ('department', models.CharField(max_length=255)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('prefix_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.prefix_name', verbose_name='คำนำหน้านาม')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
